#!/bin/sh
#
# Undeploy the environment.
#
# @author   TADOKORO Saneyuki <saneyan@mail.gfunction.com>
# @license  MIT License

[ "$(whoami)" != "root" ] && echo "Root privilege required." && exit 1

declare _dir=
declare _rall=false
declare _arch=$(uname -m)
declare -r _mntp=/mnt/archiso   # The mount point of Arch ISO (Read-only)
declare -r _dirname=$(cd $(dirname $0)/../ && pwd)

[ ! -e $_dirname/.deploy.lock ] && echo "You have not deployed the environment." && exit 1

source $_dirname/subsets/remaster-utils

while getopts d:a:X opt; do
  case $opt in
    # Destination directory.
    d) _dir=$OPTARG ;;
    # Remove contents.
    X) _rall=true ;;
    # The target architecture. It must be x86_64 or i686 architecture.
    a)
      if [[ "$OPTARG" =~ "^(x86_64|i686)$" ]]; then
        _arch=$OPTARG
      else
        echo "Specify an architecture, 'x86_64' or 'i686'"
        return 1
      fi
      ;;
  esac
done

[[ -z $_dir ]] && echo "The destination directory is required." && exit 1

readonly _dir _arch

cd $_dir/arch/$_arch
umount --verbose $_dir/mnt
umount --verbose $_mntp
rm --recursive --verbose $_mntp

if [ $_rall = true ]; then
  rm --verbose airootfs.sfs
  rm --recursive --verbose $_dir
fi

rm $_dirname/.deploy.lock

[ $? = 0 ] && echo "Done!"
